[service]
    [service.database]
    saved-path = "waifud.gob"
    min-ttl = 600

    [service.jsonapi]

    [service.telebot]
    token = ""

    [service.aria2c]
    url = "http://127.0.0.1:6800/jsonrpc"
    secret = ""